### ISSUE TITLE
small tolerance in segment3D.Intersect

### ISSUE THREAD

**Issue by armitatz** [RiSearcher/GeometRi.CSharp#1]
In the file Segment3D.cs there is a 'double small = 1E-09;'. This might look small enough but for the segments defined in the following vb code

```
Dim ds As Double

        Dim p1 As New GeometRi.Point3d(0.209369, 0.857752, 0)
        Dim p2 As New GeometRi.Point3d(0.306139, 0.828827, 0)
        Dim p3 As New GeometRi.Point3d(0.230761, 0.851433, 0)
        Dim p4 As New GeometRi.Point3d(0.327265, 0.821633, 0)
        Dim l1 As New GeometRi.Segment3d(p1, p2)
        Dim l2 As New GeometRi.Segment3d(p3, p4)
        ds = l2.DistanceTo(l1)

```
it makes the 'DistanceTo' to report the distance as 0.007953 and not as 0.0 as they intersect. They seem parallel but they are not so my suggestion would be to decrease the tolerance even more. When I run your code the DD for these two segments is 8.5318104768448066E-09.

![clipboard02](https://user-images.githubusercontent.com/28607468/33183532-e6113de0-d080-11e7-845e-4d4e0e142211.jpg)
![clipboard01](https://user-images.githubusercontent.com/28607468/33183533-e636f3a0-d080-11e7-8f0c-9f23e8b8d8d8.jpg)

**Comment by RiSearcher** [comment]
You are right. I will replace it with global tolerance property (GeometRi3D.Tolerance), which is 1E-12. It will work in this case and also everybody will be able to change the tolerance when needed. You still won't get 0.0, but 7.8E-15 is close enough.

**Comment by RiSearcher** [comment]
Fixed in v.1.3.2.
