### ISSUE TITLE
F# sample

### ISSUE THREAD

**Issue by FoggyFinder** [RiSearcher/GeometRi.CSharp#13]
I thought to add F# samples to ReadMe but dotnetfiddle doesn't run code properly due to:

```
Run-time exception (line -1): That assembly does not allow partially trusted callers.

Stack Trace:

[System.Security.SecurityException: That assembly does not allow partially trusted callers.]
   at <StartupCode$073649e0-01da-4336-a16d-58a9c7937d76>.$4ihoblhi4969.main@()
```

https://dotnetfiddle.net/kv3ntB

What do you think about adding simple test project into sample folder instead?

**Comment by RiSearcher** [comment]
Do you have any idea why this happens only with F#?

**Comment by FoggyFinder** [comment]
I have no idea. I used dotnetfiddle early for couple C# libraries and there were no any problems even for F# script.
