### ISSUE TITLE
Distance between parallel segments no calculated properly

### ISSUE THREAD

**Issue by davidarh** [RiSearcher/GeometRi.CSharp#16]
Hi,

I am calculating the distance between two parallel segments and the results are not correct. in some cases. THe segments would be something like this:

![image](https://user-images.githubusercontent.com/25058566/56842814-d8d0e600-6867-11e9-8b77-edb85f3aa905.png)

The current algorithm I believe is calculating the distance between a pair of points of both segments, and the only way I got the correct distance is by doing.

segment1.DistanceTo(segment2.ToLine);

I was able to use this modified alternative because I know the span of both segments, but I believe the DistanceTo method can be modified to correctly catch this case.

**Comment by davidarh** [comment]
Hi, I managed to get this example from the console while debugging the project I am working on:

> segment
Segment:
Point 1  -> (    399.83,     273.22,          0)
Point 2 -> (    399.83,     253.56,          0)
> lineSeg3d
Segment:
Point 1  -> (    401.53,      283.1,          0)
Point 2 -> (    401.53,      272.6,          0)
> segment.Direction
Vector3d -> (         0,    -19.667,          0)
> lineSeg3d.Direction
Vector3d -> (         0,      -10.5,          0)
> segment.DistanceTo(lineSeg3d.ToLine)
1.69999999999999
> segment.DistanceTo(lineSeg3d)
10.0202607251508

**Comment by RiSearcher** [comment]
Can you provide complete code, not just output? Because this code:

    Segment3d segment = new Segment3d(new Point3d(399.83, 273.22, 0), new Point3d(399.83, 253.56, 0));
    Segment3d lineSeg3d = new Segment3d(new Point3d(401.53, 283.1, 0), new Point3d(401.53, 272.6, 0));

    Console.WriteLine(segment.DistanceTo(lineSeg3d.ToLine));
    Console.WriteLine(segment.DistanceTo(lineSeg3d));

gives 1.69999999999999 in both cases.

**Comment by davidarh** [comment]
Let me see if I can send more information, but sending the code wouldn't work in this case, as these particular cases are reached within the context of a large process and 1000's of lines of code. I'll try sending more info later today.

**Comment by RiSearcher** [comment]
I understand that this happens somewhere inside complex code. But may be it is possible to cut it down to 50-100 lines, which still reproduce error.

Or, you may try to output the coordinates of end points by custom code, without rounding (not using default "ToString()" method).

**Comment by davidarh** [comment]
Hi, here you will find the coordinates of one of these cases:

> segment.P1.X + " - " + segment.P1.Y + " - " + segment.P1.Z
"399.827337066611 - 273.222310359762 - 0"
>  segment.P2.X + " - " + segment.P2.Y + " - " + segment.P2.Z
"399.827337066611 - 253.555611361808 - 0"
> lineSeg3d.P1.X + " - " + lineSeg3d.P1.Y + " - " + lineSeg3d.P1.Z
"400.927337066611 - 283.097310359762 - 0"
> lineSeg3d.P2.X + " - " + lineSeg3d.P2.Y + " - " + lineSeg3d.P2.Z
"400.927337066611 - 272.597320556641 - 0"
> segment.DistanceTo(lineSeg3d)
9.93607694213365
> segment.DistanceTo(lineSeg3d.ToLine)
1.10000000000002
> GeometRi.GeometRi3D.Tolerance
1E-12

**Comment by RiSearcher** [comment]
Sorry, it didn't help. I need a piece of code which I can run and get error. With your data I still get correct results.
