### ISSUE TITLE
ClosestPoint and DistanceTo from point to triangle problem

### ISSUE THREAD

**Issue by vinczet** [RiSearcher/GeometRi.CSharp#17]
Hi!
I have some MeshGeometry3D objects with lots of triangles and a Point3D point.
I would like to get the triangles from each Mesh object with the closest distance to the point and I would like to get from the closest distance triangle the closest point.
There seems to be an error in the Triangle.ClosestPoint and therefore in Triangle.DistanceTo aswell.

After I calculate the closest triangles of all the sub models and get the closest points, I draw these and the result is not what I expect.
The black lines should be the lines from the given point to the closest points of golden triangles.
I would appreciate if you helped me with this...

If it is not clear enough I will create a demo app.

Thank you!
Tamás
![Hiba1](https://user-images.githubusercontent.com/50625436/57704426-291ab700-7662-11e9-81ea-420c323e38c0.png)

**Comment by vinczet** [comment]
I created a small sample app.
I use Helix toolkit to present 3D. If you right click and move your mose you turn the camera, if you press shift and right click and move the mouse, then you move the camera. With scrolling you move forward/backward.
If you press the topmost button then random points are generated and distances are calculated to all triangles of the model. To the closest point a black line is drawn, the closest triangle's sides become yellow.

I attached 2 models. With the second model it seems working! I do not know what the difference is...
Probably the first coordinate system is normalized

[helloA.zip](https://github.com/RiSearcher/GeometRi.CSharp/files/3178910/helloA.zip)

**Comment by RiSearcher** [comment]
Hi! Thank you for providing sample application. I will try to extract non-working example from it for testing.

**Comment by RiSearcher** [comment]
Please try new version: 1.3.5.11. It should solve the problem.

**Comment by vinczet** [comment]
Hi Sergey!

Thank you! The new version works fine.
Keep up the good work!
Best regards
Tamás

________________________________
