### ISSUE TITLE
It would be nice to have a method for a Box3d if a given triangle or a part of the triangle is in the Box3d

### ISSUE THREAD

**Issue by vinczet** [RiSearcher/GeometRi.CSharp#18]
Hi,
I am working with meshes (objects built from lots of triangles) and have to determine the intersection of two meshes.
I try to divide the space to smaller and smaller cubes and check if a cube intersects any triangle from both meshes. If the edge of a cube is less than a predefined small number, than I assume that the two meshes intersect at the cube.
For this I need a method that checks if a given triangle is intersecting (or the whole triangle is inside) the space of the Box3d.
If you don't have time to write this method, would you give me any suggestions how to solve it?
Thank you!

**Comment by RiSearcher** [comment]
Please check the latest version. The code is not optimized for batch checks, but it should work.

**Comment by vinczet** [comment]
Hi Sergey,
it seems to work, thank you!
I did not do much testing, but for the few tests it gave the correct value.

Thank you and keep up the good work!
Tamás

________________________________
