### ISSUE TITLE
Issue with DistanceTo(Point3d p) in particular cases

### ISSUE THREAD

**Issue by AntoineC4Ci** [RiSearcher/GeometRi.CSharp#19]
I noticed an issue when testing the Triangle.DistanceTo(obj) function. It seemed to me that it is a major issue, so I took the time to submit this issue.

From the basic tests i did, it does not work properly if the normal projection of the point on the Triangle.ToPlane belongs to the Triangle.

I don't know if I am clear enough, so i copy pasted a small testing routine that should be explicit enough.

    class Testing
    {
        public static void Main()
        {

            Point3d p0 = new Point3d(0, 0, 0);
            Point3d p1 = new Point3d(2, 0, 0);
            Point3d p2 = new Point3d(0, 2, 0);
            Point3d pCentre = new Point3d(1, 1, 8);

            Point3d pOnTri1 = new Point3d();
            Point3d pOnTri2 = new Point3d();
            Point3d pOnCir1 = new Point3d();
            Point3d pOnCir2 = new Point3d();

            // plane objects
            Triangle t = new Triangle(p0, p1, p2);
            Circle3d c = new Circle3d(pCentre, 2, new Vector3d(p0, p1));

            // reference point#1 to caclulate the min dist from
            Point3d pRef_1 = new Point3d(1, 1, 4);

            // in this config, should return pRef.Z = 4 
            double dist1_1 = t.DistanceTo(pRef_1); // But returns 0
            // in this config, should return pCentre.Z - c.R ) = 8-2 = 6.  
            double dist2_1 = t.DistanceTo(c, out pOnTri1, out pOnCir1); // but returns 8. pOnTri1 is good, but pOnCir is (1,1,8) instead of (1,1,6)
            // returns '2' as expected 
            double dist3_1 = c.DistanceTo(pRef_1);
            //returns a good closest point,i.e. (1,1,0)
            var closestP1 = t.ClosestPoint(pRef_1);

            // reference point#2 to calculate the min dist from (whith a small offset)
            Point3d pRef_2 = new Point3d(1.00001, 1, 4);
            //returns approx. '4' as expected. If we type (0.00009, 1, 4), it fails again
            double dist1_2 = t.DistanceTo(pRef_2);
            //return a good closest point (1,1,0)
            var closestP2 = t.ClosestPoint(pRef_2);
        }
    }
`
For the function t.DistanceTo(Point3D p), I wonder why you do not simply return the length of the Segment3d (p, t.ClosestPoint), as this function seems to work.

Thank you for your feedback.

**Comment by RiSearcher** [comment]
Thank you very much for reporting this bug. It should be fixed now.

**Comment by AntoineC4Ci** [comment]
it is fixed from what i tested.

Thanks !!!
