### ISSUE TITLE
Coordinate rotation/translation does not have effect when creating objects

### ISSUE THREAD

**Issue by AntoineC4Ci** [RiSearcher/GeometRi.CSharp#21]
Hello,

 I was testing how the coordinate system works, and noticed, that after rotating a coordinate system, it does work on the .Xaxis, .Yaxis and .Zaxis of this coordinate system, but after that, it seem that the rotation is somehow "forgotten" when i create for instance a Point3d object.

example test code below :       

   ```
//  Coord Test
            Point3d Origin1 = new Point3d(1, 1, 0);
            Vector3d x1 = new Vector3d(0,1, 0);
            Vector3d y1 = new Vector3d(-1, 0, 0);

            Coord3d coord1 = new Coord3d(Origin1, x1, y1, "Coord1");
            coord1.Rotate(coord1.Zaxis, Math.PI/2);
            Point3d p_test = new Point3d(1, 0, 0, coord1); // ISSUE : does not apply the rotated coordinate system (expect (0,-1,0) instead of (0,1,0) in the global coord system)
            Point3d p_test2 = p_test.ConvertToGlobal();

```

Thank you for your feedback !

PS (a bit out of topic): Lets say we previously created a Point3d according to a custom coordinate system. How does it behave after rotating/translating this custom coordinate system ?
I think that it does not change any coordinate value X,Y,Z, of the Point3d, but this point still refers to the same coordinate system that has been changed ... seems pretty dangerous to me :).

**Comment by RiSearcher** [comment]
Hi!
It seems that everything working correctly: origin of your local coordinate system is in point (1,1,0), and after rotation the X axis is oriented in opposite direction of global X axis. Therefore the point (1,0,0) in local CS will have coordinates (0,1,0) in global CS.
Rotation of the CS changes only the axes orientation, the origin does not move.

P.S. If some point has local reference CS and this CS is rotated, the point will move with this local CS. Seems quite logical. And dangerous, yes :) I would not change local CS after it is referenced by some other objects, this may have unwanted side effects. Unless you really want to do this.

**Comment by AntoineC4Ci** [comment]
You are right !! I do not know how I messed myself with my testing.

Sorry for the disturbance ...
