### ISSUE TITLE
Segment3d problem with ClosestPoint to a Point3d

### ISSUE THREAD

**Issue by vinczet** [RiSearcher/GeometRi.CSharp#23]
Hi Sergey,
I have run into a problem when I was calculating closest points on segments from a given point. I discovered that sometimes I get different result if I change the order of P1 and P2 when instantiating a Segment3d.
If I run the code below I wait that dst1 and dst2 should be the same and cp1 and cp2 also, but they are **not**!
```
var p1 = new Point3d(23179.004, 12816.489, -20.395);
var p2 = new Point3d(22563.294, 13022.342, 90.848);
var sg1 = new Segment3d(p1, p2);
var sg2 = new Segment3d(p2, p1);
var pnt = new Point3d(23036.287595521906, 12779.633961461441, -5.2532084155503256);

var dst1 = sg1.DistanceTo(pnt);
var dst2 = sg2.DistanceTo(pnt);
var cp1 = sg1.ClosestPoint(pnt);
var cp2 = sg2.ClosestPoint(pnt);

```
Would you check this and tell me if I do something wrong?
Thank you very much!
Tamás

Update:
If I set  GeometRi3D.UseAbsoluteTolerance = false; then the results are good. If I divide all coordinates by 1.000, then the results are good (without setting UseAbsoluteTolerance to false).
By default the tolerance is 1E-12. If I set it to 1E-24 then the results are the same but they are wrong. If I set the Tolerance to 1E-9 then the results are good.
I am confused.

**Comment by RiSearcher** [comment]
Hi!
The default absolute tolerance 1e-12 is too low to work with such large numbers as in your example. Due to round-off errors the last digits in some internal calculations are different, but the last digit for your number is exactly at 12 position. This is why results are Ok when you decrease accuracy, or use relative tolerance option.
