### ISSUE TITLE
Unexpected results with large dimention geometries

### ISSUE THREAD

**Issue by AntoineC4Ci** [RiSearcher/GeometRi.CSharp#24]
Hello there,

I noticed pretty critical unexpected results when large dimension objects are manipulated.
For more details and documentation, see code below (unit test functions). 
_I do hope that I am clear enough. I am not an experienced developer, and more an engineer that tries to develop and to give feedback as clean as possible._

I am aware that the tolerance parameter can be a way to kind of solve the issue, but for my use, i **do** need a pretty fine tolerance, while manipulating significantly "big" geometrical objects.

1) I already took a look into the GeometRi functions. For the Triangle Intersection error (see `public void testTriangleIntersection()`), i do not have any clue yet about where the issue comes from.
2) For the Coplanar error (see` testCoplanar()`), I think I found where it comes from (see below)

```using GeometRi;
using Microsoft.VisualStudio.TestTools.UnitTesting;


namespace Namespace   

 [TestClass]
    public class TestHighNumberTolerances
    {
        [TestMethod]
        public void testTriangleIntersection()
        {
            Point3d a = new Point3d(18508, 7020, 3193);
            Point3d b = new Point3d(-925, -162, -233);
            Point3d c = new Point3d(-858, -349, -221);

            Triangle t = new Triangle(a, b, c);

            Plane3d plane = new Plane3d(new Point3d(0, 200, 0), new Vector3d(0, 1, 0));

            Segment3d s0 = new Segment3d(a, b);
            Segment3d s1 = new Segment3d(a, c);


            object result = t.IntersectionWith(plane); //while we expect a segment3d, it can be null, or point3d like here

            object inter1 = s0.IntersectionWith(plane); //returns Point3d
            object inter2 = s1.IntersectionWith(plane);//returns another distinct Point3d 
            Segment3d expectedResult = new Segment3d((Point3d)inter1, (Point3d)inter2); //segment3d with a >0 length

            Assert.IsTrue(expectedResult.Equals(result)); //Error
        }

        [TestMethod]
        public void testCoplanar()
        {
            Point3d a = new Point3d(-1000, 180, -70);
            Point3d b = new Point3d(20000, 180, -70);
            Point3d c = new Point3d(20000, 180, 70);
            Point3d d = new Point3d(-1000, 180, 70);

            Triangle t0 = new Triangle(a, b, c);
            Triangle t1 = new Triangle(b, c, d);

            Rotation rz = new Rotation(Coord3d.GlobalCS.Zaxis, 30 * System.Math.PI / 180);
            Rotation ry = new Rotation(Coord3d.GlobalCS.Yaxis, 10 * System.Math.PI / 180);

            Point3d p = new Point3d(0, 0, 0);

            t0 = t0.Rotate(rz, p);
            t1 = t1.Rotate(rz, p);
            t0 = t0.Rotate(ry, p);
            t1 = t1.Rotate(ry, p);

            bool areEqual = t0.ToPlane.Equals(t1.ToPlane); //returns false (expected true)
            bool areCoplanar = t0.IsCoplanarTo(t1);//returns false (expected true)
            Assert.IsTrue(areEqual); //Error
            Assert.IsTrue(areCoplanar); //Error

            bool areEqual_fix = t0.ToPlane.Equals_fix(t1.ToPlane); //returns true
            bool areCoplanar_fix = t0.IsCoplanarTo_fix(t1); //returns true
        }

        public static bool Equals_fix(this Plane3d p0, Plane3d p1)
        {
            bool isCoplanar;
            if (p1.Normal.IsParallelTo(p0.Normal))
            {
                if (p1.Point.Equals(p0.Point))
                    isCoplanar = true;
                else
                {
                    var v = new Vector3d(p1.Point, p0.Point).Normalized;
                    double a = v.Dot(p0.Normal.Normalized);
                    isCoplanar = a <= GeometRi3D.DefaultTolerance;
                }
            }
            else
                isCoplanar = false;
            return isCoplanar;
        }

        public static bool IsCoplanarTo_fix(this IPlanarObject p1, IPlanarObject p2)
        {
            return p1.ToPlane.Equals_fix(p2.ToPlane);
        }
```

The "IsCoplanar" issue comes in my opinion from these lines (Point3d), with the square root that makes the result to quickly exceed the GeometRi3D.Tolerance.

```
public bool BelongsTo(Plane3d s)
        {
            s.SetCoord(Coord);
            if (GeometRi3D.UseAbsoluteTolerance)
            {
                return Math.Abs(s.A * X + s.B * Y + s.C * Z + s.D) / Math.Sqrt(s.A * s.A + s.B * s.B + s.C * s.C) < GeometRi3D.Tolerance;
            }

            double num = DistanceTo(_coord.Origin);
            if (num > 0.0)
            {
                return Math.Abs(s.A * X + s.B * Y + s.C * Z + s.D) / Math.Sqrt(s.A * s.A + s.B * s.B + s.C * s.C) / num < GeometRi3D.Tolerance;
            }

            return Math.Abs(s.A * X + s.B * Y + s.C * Z + s.D) / Math.Sqrt(s.A * s.A + s.B * s.B + s.C * s.C) < GeometRi3D.Tolerance;
        }
```

The IsEqual Issue comes in my opinion from these lines (Point3d), because the distance exceed the Tolerance.

```
        public double DistanceTo(Line3d l)
        {
            return new Vector3d(this, l._point).Cross(l._dir).Norm / l._dir.Norm;
        }
```

Instead, it would be clever to use the logical functions that are based as often as possible on normalized logics that allow us to avoid as mush as possible to use very big (or also very small) double values (see my proposals for the functions "IsCoplanar_Fix" ans "Equals_fix".

----

In general, I would highly suggest that the `IPlanarObject.Normal`, `ILinearObject.Direction` (and so on) should be Normalized vector only.
Also, in many functions too we are manipulating non Normalized vectors then it could be. This is in my opinion often not coherent with the notion of Tolerance, especially when talking about Vector3d.Cross(vector3d) or vector3d.Dot(vector3d).

For instance, when, we are checking if two lines are crossing, it does not matter how these lines have been created. After the line creation, we Have a Point3d, and a Vector3d Direction. Sadly this Direction is not Normalized, and it leads to an isue with these lines : 

```
 public virtual Point3d PerpendicularTo(Line3d l)
        {
            Vector3d toVector = Point.ToVector;
            Vector3d toVector2 = l.Point.ToVector;
            Vector3d direction = Direction;
            Vector3d direction2 = l.Direction;
            if (direction.Cross(direction2).Norm > GeometRi3D.Tolerance)
            {
                toVector = toVector2 + (toVector2 - toVector) * direction.Cross(direction.Cross(direction2)) / (direction * direction2.Cross(direction.Cross(direction2))) * direction2;
                return toVector.ToPoint;
            }

            return l.Point;
        }
```
Multiple `.Cross` functions induce wrong results with big double values, where it could be easily right considering normalized vectors.

Please ask if you need help or further testings.
Regards, and thank you by advance.

**Comment by RiSearcher** [comment]
Hi!
You are right, normalized values would be better. I will try to do it this week and, if everything will be Ok, new version will be released soon.

**Comment by RiSearcher** [comment]
Hi!
I have implemented your suggestions for 'Equals' and 'Coplanar' functions, thank you! And normalized 'normal' and 'direction' properties.
However, it didn't help with your first test examples. Since the accuracy of double is up to 16 digits and your object is about 10000 in length, generally you can not expect accuracy of 10E-12. 
I rewrote triangle intersection with plane and line, and now it works with your test data, but there are many other places in the code where tolerance based checks are used. I would increase the tolerance for such calculations.

**Comment by RiSearcher** [comment]
Hi!
There must be some misunderstanding.
Plane normal is now normalized in constructor. And triangle normal is normalized, see https://github.com/RiSearcher/GeometRi.CSharp/blob/master/GeometRi/Triangle.cs
And I have included your tests to the project and they pass when I run tests: master/GeometRi.Tests/NormalizeTest.cs

**Comment by AntoineC4Ci** [comment]
OH !

I realized that Visual Studio failed updating properly the package :). Sorry for the disturbance.

So, for the first unit test, if i am right, only the Segment3d.Equals(Segment3d s) is failing due to tolerance.

**Comment by RiSearcher** [comment]
I forgot I switched to relative tolerance in first test. So, yes, it fails if default absolute tolerance (1e-12) is used. However, 1e-11 is sufficient to pass. Probably, 1e-12 is too restrictive.

**Comment by RiSearcher** [comment]
Hi!
Fixed in last commit. Thank you for reporting.

**Comment by AntoineC4Ci** [comment]
Hi,

Sadly, the fix does not work 100% properly. Actually, I looked at the code, but did not managed to guess where the issue comes from.
See anther more complete unit test below:

```
       [TestMethod]
        public void SimpleAngleTest2()
        {
            Point3d p0 = new Point3d(0, 100, 0);
            Point3d p1 = new Point3d(0, 100, -100);

            Rotation r = new Rotation(Coord3d.GlobalCS.Yaxis, 30 * Math.PI / 180);
            p1 = p1.Rotate(r, p0);

            Segment3d s = new Segment3d(p0, p1);
            double angle = s.AngleToDeg(Coord3d.GlobalCS.Zaxis);
            //Assert.Equals(30, angle); //error because of imprecision. It was OK before the initial fixes of the issue #24. 

            angle = s.AngleToDeg(Coord3d.GlobalCS.Zaxis.Mult(-80)); //expect 30, but equals 0 :(
            //Assert.Equals(30, angle); // error.  
        }
```

**Comment by RiSearcher** [comment]
Thanks again!!!
"Premature optimization is the root of all evil" - I removed normalization in the angle computation method, but completely forgot that vector also has direction property... which should be normalized now.

**Comment by AntoineC4Ci** [comment]
:)
I had a bunch of unit tests, so it was easy to come back to you with a detailed report :).

Thanks for the quick fixes ! It seems all right now :)
Regards
