### ISSUE TITLE
Segment to triangle distance with points

### ISSUE THREAD

**Issue by vinczet** [RiSearcher/GeometRi.CSharp#25]
I follow the development of this library. I am a satisfied user of this! :)
Would it be difficult to get the distance and the closest points between a segment and a triangle?
And then later the distance and closest points between two triangles?
Thank you!

**Comment by RiSearcher** [comment]
Hi!
I'll try to do this, but probably a bit later. Will be busy for next two weeks.

**Comment by vinczet** [comment]
Hi!
Thank you.
I found this c++ library [GeometricTools](https://github.com/davideberly/GeometricTools) which covers these distances if you need insporation.
Regards
Tamás

**Comment by RiSearcher** [comment]
Hi!
Please check latest version.

**Comment by vinczet** [comment]
Hi Sergey,

Thank you! I am checking it.

Regards
Tamás
________________________________
