### ISSUE TITLE
Point3d within Triangle is considered to be some distance away

### ISSUE THREAD

**Issue by JMolenkamp** [RiSearcher/GeometRi.CSharp#26]
`Point3d` instances that are clearly part of a `Triangle` are sometimes considered to be some distance away when using `Point3d.DistanceTo(Triangle t)` or `Triangle.DistanceTo(Point3d p)`.

Example:
``` csharp
var triangle = new Triangle(
    new Point3d(0, 0, 0),
    new Point3d(10000, 0, 0),
    new Point3d(0, 10000, 0));

var point = new Point3d(3286.5999999974479, 5000, 0);

double distance = triangle.DistanceTo(point);   // Expected: 0, Actual: 1211.55...
```

Sample code used to produce the above point:
``` csharp
double size = 10000;
double step = size / 100000;
double p = size / 2;

Triangle triangle = new Triangle(
    new Point3d(0, 0, 0),
    new Point3d(size, 0, 0),
    new Point3d(0, size, 0));

for (double px = p; px > 0 ; px -= step)
{
    Point3d point = new Point3d(px, p, 0);
    double distance = triangle.DistanceTo(point);

    if (distance > GeometRi3D.Tolerance)
    {
        throw new Exception("Point that is part of triangle is considered to be some distance away");
    }
}
```

`Triangle.DistanceTo(Point3d p)` is fixed to usage of absolute tolerances. `Triangle._PointLocation(Point3d p)` does not consider its calculation to be almost equal, when using absolute tolerances, finally resulting in a calculation to the closest edge in `Triangle.DistanceTo(Point3d p)`.

The calculation with relative tolerances in `Triangle._PointLocation(Point3d p)` does consider the point to be within the triangle. But this calculation will never be used.

Might be related to issues posted by @AntoineC4Ci

**Comment by RiSearcher** [comment]
Hi!
Thank you for pointing at this problem. I will fix it soon.
Currently the best solution is to increase the tolerance working with large objects.

**Comment by JMolenkamp** [comment]
I assumed that `GeometRi3D.DefaultTolerance` (which is used to set `GeometRi3D.Tolerance`) was read-only, but I just noticed that it has a set accessor. So I can simply apply a relative tolerance outside of the call. 
Thanks for pointing me in this direction.
