### ISSUE TITLE
IntersectionWith error when lines are parallel

### ISSUE THREAD

**Issue by maisoui** [RiSearcher/GeometRi.CSharp#27]
Hi,

If you try to get intersection of 2 parallel lines, it will crash with a "NullReferenceException".
In method "IntersectionWith" of Line3d (line 258) :

`Point3d p = l.PerpendicularTo(this);`

"p" is null and it's not checked in the following line.
[compiled on net7.0 (C# 11.0)]

Best regards,
Jonathan

**Comment by RiSearcher** [comment]
Thank you! Fixed in latest release.
