### ISSUE TITLE
How to get coord3D from plane3D ?

### ISSUE THREAD

**Issue by cyrilpreiss** [RiSearcher/GeometRi.CSharp#31]
Hi,
i have a planed3D (using the a,b,c et d values) and i would like the get a ccord3D where the plane3D is the 0xy plane.
how can i do ?

**Comment by RiSearcher** [comment]
Hi!
If you need to create arbitrary CS aligned with plane, you can do like that:
`
            Plane3d p = new Plane3d(1, 1, 1, 1);
            Point3d point = Coord3d.GlobalCS.Origin;
            Point3d projection = point.ProjectionTo(p);
            Vector3d z = p.Normal;
            Vector3d x = z.OrthogonalVector;
            Vector3d y = x.Cross(z);
            Coord3d new_coord = new Coord3d(projection, x, y);
`
If you already have specific point where origin of new CS should be located, use it instead of 'projection' point.
