### ISSUE TITLE
Intersection of a segment with a circle returns an unexpected result

### ISSUE THREAD

**Issue by danmik** [RiSearcher/GeometRi.CSharp#32]
Hi. I encountered a possible issue with intersecting a line segment with a circle. The intersection result seems to be in a different coordinate system (?).

```csharp
var circle = new Circle3d(new(400, 300, 0), 15, new(0, 0, 1));
var segment = new Segment3d(new(400, 320, 0), new(400, 310, 0));

var intersection = segment.IntersectionWith(circle);
var intersectionSegment = (Segment3d)intersection;

Console.WriteLine(intersectionSegment.ToString());
Console.WriteLine("");
Console.WriteLine($"P1.X: {intersectionSegment.P1.X}");
Console.WriteLine($"P1.Y: {intersectionSegment.P1.Y}");
```
This prints:
```
Segment:
Point 1  -> (       400,        310,          0)
Point 2 -> (       400,        315,          0)

P1.X: 25
P1.Y: 0
```
The output of the `ToString()` is the result I would expect, but accessing the segment's points (`P1` and `P2`) gives me different values.

It works correctly if I call `ConvertTo(null)` on the segment's points:
```csharp
var p1 = intersectionSegment.P1.ConvertTo(null);
Console.WriteLine($"p1.X: {p1.X}");
Console.WriteLine($"p1.Y: {p1.Y}");
```
Prints:
```
p1.X: 400
p1.Y: 310
```
Is it intended to work this way? Intersecting other types (e.g. `Segment3d` with a `Line3d`) seems to give me expected results without calling `ConvertTo(null)`.

I'm using version 1.4.0.5 and .NET 8.

**Comment by RiSearcher** [comment]
Hi. Yes, this is intended behavior. If a segment is coplanar with the circle, the problem reduces to 2D. Local coordinate system (CS) aligned with the circle is created internally, and results are given in this local CS. If you need to work with coordinates, you have to explicitly convert results to coordinate system you work with.
And this is true for some other methods. In GeometRi each object can be defined in different CSs and all transformations are performed internally under the hood, the user does not have to keep track of all CSs and convert objects from one CS to another. The down side - results can be returned in different CS too.

**Comment by danmik** [comment]
Understood, thank you.
