### ISSUE TITLE
Vector3d.AngleTo method misleading

### ISSUE THREAD

**Issue by jbooth88** [RiSearcher/GeometRi.CSharp#33]
`var angle = vector.Coord.Xaxis.AngleTo(vector);`

Not sure if I'm explaining this right.

The above method returns the angle between the x axis and the vector, but the method name implies that the result should be the directional angle from the x-axis to the vector (hence "AngleTo"). The difference is that the method currently returns the absolute value of the angle without direction, meaning vectors (1,-1,0) and (1,1,0) both return pi/4 and there's no indication of rotation from v1 to v2. I believe standard convention is that a positive angle implies CCW rotation and a negative angle implies CW rotation.

**Comment by RiSearcher** [comment]
Hi. This standard convention works in 2D space. In 3D space you also need to specify axis of rotation, and this is what Rotation object do. The name "AngleTo" may be misleading, but probably it is to late to rename it.
