### ISSUE TITLE
Operator == with null

### ISSUE THREAD

**Issue by maisoui** [RiSearcher/GeometRi.CSharp#4]
Hi,
Should not we check if the object is not null in the operators == before calling the Equals method?
The following code crashes:
`Point3d point = null;
if(point == null)
{			
}`

Best regards,
Jonathan

**Comment by RiSearcher** [comment]
Hi,
You are right, this test for null should be added. I will do it for all objects.

**Comment by RiSearcher** [comment]
Fixed in release v1.3.5.5.
