### ISSUE TITLE
Distance from point to plane?

### ISSUE THREAD

**Issue by flycast** [RiSearcher/GeometRi.CSharp#8]
Not an issue. I just discovered this library today. Looks like it has a lot of really good features that Accord.net does not have (doubles instead of floats, intersections between planes and other entities, etc.).

My question...Is there a way to calculate the distance between a point and a plane? I need to tell if a point in 3D space is between two planes.

**Comment by RiSearcher** [comment]
point.DistanceTo(plane) will return shortest distance to plane in 3D space.

You still will need to do some analysis to tell if a point is between two (parallel?) planes. What I would do:
1. check if two planes are parallel - plane1.IsParallelTo(plane2)
2. calculate distance between any point on one plane to second plane - plane1.Point.DistanceTo(plane2)
3. compare distance between planes and sum of distances between your point and both planes.

**Comment by flycast** [comment]
Thank you so much!
